# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e7ad4e86b4a97280c6fe63dfc6e7da78acff363d2e100a1f2f31563ca8c0f026597db2936f9203a828d52654dd70f95b3e60cf8ee382aeeed2931e014066403

test:
  secret_key_base: 2930b8a264aac503af61c7e1acb509bb42f81ed2c392e372fce723b2fc74f0d532682442e7e450fd004a3fe17ea1d35f89590d377d59688acf7bffebc653d6d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
